# Generated by Django 4.2 on 2024-10-01 05:24

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.folder
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='package_icons/')),
                ('icon_label', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('exclusions', models.TextField()),
                ('notes', models.TextField()),
                ('promotions', models.TextField()),
                ('honeymoon_offer', models.TextField()),
                ('cover_photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_cover', to=settings.FILER_IMAGE_MODEL)),
                ('image_folder', filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_image_folders', to='filer.folder')),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField()),
                ('extended_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='sns.roomcategory')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='sns.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='sns.packagetype'),
        ),
        migrations.AddField(
            model_name='package',
            name='video_folder',
            field=filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_video_folders', to='filer.folder'),
        ),
    ]
