# Generated by Django 4.2 on 2024-10-01 05:33

from django.db import migrations
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='media_folder',
            field=filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_media_folders', to='filer.folder'),
        ),
    ]
